FROM node:10.0.0

RUN mkdir /usr/src/server
WORKDIR /usr/src/server

ENV PATH /usr/src/server/node_modules/.bin:$PATH

COPY server/package.json /usr/src/server/package.json

RUN npm install ./server/package.json

CMD npm start